image: node:16

cache:
  key:
    files:
      - yarn.lock
  paths:
    - node_modules/

stages:
  - qa
  - deploy

lint:
  stage: qa
  script:
    - yarn install
    - yarn lint

test:
  stage: qa
  script:
    - yarn install
    - yarn test

build:
  stage: qa
  script:
    - yarn install
    - yarn build-all

# Deploy docs to Gitlab pages
pages:
  stage: deploy
  only:
    - master
  script:
    - yarn install
    - yarn docs
    - mv docs public
  artifacts:
    paths:
      - public
